import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

// Update `site` to the real domain before deploying (used for canonical URLs + sitemap).
// Sitemap is generated by src/pages/sitemap.xml.ts (the official integration currently
// breaks when the project path contains a space).
export default defineConfig({
  site: 'https://diapason.pages.dev',
  integrations: [tailwind({ applyBaseStyles: false })],
});
